services:

  mongo:
    image: mongo:7
    container_name: dev-mongo

    volumes:
      - mongo_data:/data/db

    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--eval",
          "db.adminCommand('ping')"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: ./backend

    image: dev-backend:latest

    container_name: dev-backend

    environment:
      PORT: 4000
      MONGO_URL: mongodb://mongo:27017
      DB_NAME: devops_lab
      NODE_ENV: production

    depends_on:
      mongo:
        condition: service_healthy

    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "-q",
          "http://127.0.0.1:4000/health"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  frontend:
    build:
      context: ./frontend

    image: dev-frontend:latest

    container_name: dev-frontend

    restart: unless-stopped


  nginx:
    build:
      context: ./nginx

    image: dev-nginx:latest

    container_name: dev-nginx

    ports:
      - "80:80"

    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_healthy

    restart: unless-stopped

volumes:
  mongo_data:
